version: '3.9'

services:
  qxgametool-server:
    image: qxgametool-server
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_PATH: "${BASE_HTML_PATH}"
        EXTERNAL_SERVER_PORT: "${EXTERNAL_SERVER_PORT}"
    ports:
      - "${EXTERNAL_SERVER_PORT}:${EXTERNAL_SERVER_PORT}"
